// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.common.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "map.common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace telenav {
namespace proto {
namespace map {

void protobuf_ShutdownFile_map_2ecommon_2eproto() {
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_map_2ecommon_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_map_2ecommon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_map_2ecommon_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_map_2ecommon_2eproto_once_);
void protobuf_AddDesc_map_2ecommon_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_map_2ecommon_2eproto_once_,
                 &protobuf_AddDesc_map_2ecommon_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_map_2ecommon_2eproto {
  StaticDescriptorInitializer_map_2ecommon_2eproto() {
    protobuf_AddDesc_map_2ecommon_2eproto();
  }
} static_descriptor_initializer_map_2ecommon_2eproto_;
#endif
bool RoadType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
      return true;
    default:
      return false;
  }
}

bool MapServiceStatus_IsValid(int value) {
  switch(value) {
    case 11200:
    case 11204:
    case 11400:
    case 11404:
    case 11500:
    case 11503:
    case 11504:
    case 11510:
    case 11511:
    case 11512:
    case 11513:
    case 11601:
    case 11602:
    case 11603:
    case 11604:
    case 11605:
    case 11606:
    case 11607:
    case 11611:
    case 11612:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace map
}  // namespace proto
}  // namespace telenav
}  // namespace com

// @@protoc_insertion_point(global_scope)
